### ISSUE TITLE
Implementing tests 

### ISSUE THREAD

**Issue by lore157** [lore157/stock_market#13]
Testing the functions contained in dbmanager.py

**Comment by lore157** [comment]
Implemented a test for ReadCompaniesCsv function in main.py and Check_new_username in dbmanager.py but they are not working

**Comment by IvoryTower48** [comment]
After fixing the folder structure of the project, the tests concerning open_and_create() from dbmanager.py are running and succeeding. 0571a80b12daad9e51220a10057b3aaace1a8305
